#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp /tmp/resource-in.XXXX)
cat > "${payload}" <&0

uri=$(jq -r '.source.uri // ""' < $payload)

echo '[{"version": "1.0"}]'
